#!/usr/bin/env bash
# This is a bash script that transfers a file from the client to a server using scp.

if [ $# -lt 4 ]; then
  echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
  exit 1
fi

scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3"@"$2":~

