#!/usr/bin/env bash

# Install the nginx web server
apt-get update
apt-get -y install nginx

# Start the nginx service
service nginx start

# Configure the nginx to listen on the port 80
sed -i 's/listen\s*80\s*default_server;/listen 80 default_server;\n\n\t# Configured by script\n\treturn 200 "Hello World!";/' /etc/nginx/sites-available/default

# Reload the nginx configuration
service nginx reload

