#!/usr/bin/env bash

echo "USER   PID  %CPU  %MEM  VSZ      RSS   TTY   STAT  START  TIME  COMMAND"

ps axo user,pid,%cpu,%mem,vsz,rss,tty,stat,start,time,comm | awk '{printf("%-6s %5s %5s %5s %8s %8s %-7s %-5s %-6s %-7s %s\n", $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)}'

