#!/usr/bin/env bash
# This is a a Bash script that displays To infinity and beyond indefinitely.
# requirement - In between each iteration of the loop, add a sleep 2

while :
do
    echo "To infinity and beyond"
    sleep 2
done


