#!/usr/bin/env bash
# This script displays 'To infinity and beyond' indefinitely
# Requirement - In between each iteration of the loop, add a sleep 2

function invincible() {
  echo "I am invincible!!!"
  exit 0
}

trap invincible SIGTERM

while true; do
  echo "To infinity and beyond"
  sleep 2
done
