#!/usr/bin/env bash
# Bash script that displays numbers from 1 to 20, displays 4 and then bad luck from China for the 4th loop iteration, displays 9 and then bad luck from Japan for the 9th loop iteration, displays 17 and then bad luck from Italy for the 17th loop iteration.

count=1
while [ $count -le 20 ] #using the while loop to iterate from 1 to 20 with count to keep track of the iteration. 
do
  case $count in # we use the case statement to check the value of the count and display the appropriate message.
    4)
      echo "4"
      echo "bad luck from China" # if count is 4 display bad luck from China.
      ;;
    9)
      echo "9"
      echo "bad luck from Japan" # if count is 9 display bad luck from Japan.
      ;;
    17)
      echo "17"
      echo "bad luck from Italy" # if count is 17 display bad luck from Italy.
      ;;
    *)
      echo $count # Otherwise we display the value of the count.
      ;;
  esac
  
  count=$((count+1))
done

