#!/usr/bin/env bash
# Bash script that displays the time for 12 hours and 59 minutes, display hours from 0 to 12 and then display minutes from 1 to 59. we must use only the while loop

while [ $hour -le 12 ]; do #this while loop iterates the hour while loop from 0 - 12.
	echo "Hour : $hour"
	minute=1
	while [ $minute -le 59 ]; do #this while loop iterates the minutes while loop from 1 to 59.
	  if [ $minute -lt 10 ]; then #the if statement is used to check if the minutes is less than 10 and then display them without adding the 0 ahead of it. 
		  printf "%d\n" $minute
	  else
		  printf "%02d\n" $minute
	  fi
  done
done
