#!/usr/bin/env bash
# A Bash script that configures an Ubuntu server with the below requirements.

echo "127.0.0.2 localhost" >> /etc/hosts

echo "nameserver 8.8.8.8" > /etc/resolv.conf
echo "nameserver 8.8.4.4" >> /etc/resolv.conf
echo "nameserver 208.67.222.222" >> /etc/resolv.conf
echo "nameserver 208.67.220.220" >> /etc/resolv.conf
echo "nameserver 2620:0:ccc::2" >> /etc/resolv.conf
echo "nameserver 2620:0:ccd::2" >> /etc/resolv.conf

service network-manager restart
